// plantMasterList.js
export const plantMasterList = {
  'A-APB05': { name: 'ASPHALT PAVER BITELLI BB691', type: 'Asphalt Paver', fuelType: 'Diesel', category: 'paving' },
  'A-APD06': { name: 'ASPHALT PAVER DYNAPAC DF145P', type: 'Asphalt Paver', fuelType: 'Diesel', category: 'paving' },
  'A-APD07': { name: 'ASPHALT PAVER DYNAPAC DF145P', type: 'Asphalt Paver', fuelType: 'Diesel', category: 'paving' },
  'A-APD08': { name: 'ASPHALT PAVER DYNAPAC F161-8W', type: 'Asphalt Paver', fuelType: 'Diesel', category: 'paving' },
  'A-APD09': { name: 'ASPHALT PAVER DYNAPAC DF145P', type: 'Asphalt Paver', fuelType: 'Diesel', category: 'paving' },
  'A-APD11': { name: 'ASPHALT PAVER DYNAPAC DF145P', type: 'Asphalt Paver', fuelType: 'Diesel', category: 'paving' },
  'A-APN01': { name: 'ASPHALT PAVER NIGATA', type: 'Asphalt Paver', fuelType: 'Diesel', category: 'paving' },
  'A-APV10': { name: 'ASPHALT PAVER VOGELE 1800 SPRAY JET', type: 'Asphalt Paver', fuelType: 'Diesel', category: 'paving' },
  'A-APP02': { name: 'ASPHALT MIXING PLANT MOBILE 40tph', type: 'Asphalt Plant', fuelType: 'Diesel', category: 'plant' },
  'A-APP03': { name: 'ASPHALT MIXING PLANT MOBILE 60tph', type: 'Asphalt Plant', fuelType: 'Diesel', category: 'plant' },
  'A-APP04': { name: 'ASPHALT MIXING PLANT AMMANN 140TPH', type: 'Asphalt Plant', fuelType: 'Diesel', category: 'plant' },
  'A-APP05': { name: 'ASPHALT MIXING PLANT AMMANN 140TPH', type: 'Asphalt Plant', fuelType: 'Diesel', category: 'plant' },
  'A-APP06': { name: 'ASPHALT MIXING PLANT AMMANN 140TPH', type: 'Asphalt Plant', fuelType: 'Diesel', category: 'plant' },
  'A-ASR01': { name: 'ASPHALT SHUTTLE-BUGGY ROAD-TEC SB2500', type: 'Shuttle Buggy', fuelType: 'Diesel', category: 'paving' },
  'A-ASR02': { name: 'ASPHALT SHUTTLE-BUGGY ROAD-TEC SB2500', type: 'Shuttle Buggy', fuelType: 'Diesel', category: 'paving' },
  'A-BBS03': { name: 'BUS MBENZ SPRINTER 23 SEATER', type: 'Bus', fuelType: 'Diesel', category: 'transport' },
  'A-BBS04': { name: 'BUS MBENZ SPRINTER 23 SEATER', type: 'Bus', fuelType: 'Diesel', category: 'transport' },
  'A-BDT02': { name: 'BITUMEN TRAILER 1kl', type: 'Bitumen Trailer', fuelType: 'Bitumen', category: 'specialized' },
  'A-BDT06': { name: 'CRACKSEALING TRAILER', type: 'Cracksealing Trailer', fuelType: 'Diesel', category: 'specialized' },
  'A-BEP01': { name: 'BITUMEN EMULSION PLANT', type: 'Emulsion Plant', fuelType: 'Diesel', category: 'plant' },
  'A-BEP02': { name: 'BITUMEN EMULSION PLANT', type: 'Emulsion Plant', fuelType: 'Diesel', category: 'plant' },
  'A-BNS08': { name: '0.5 TONNE BAKKIE 4X2 NISSAN', type: 'Bakkie', fuelType: 'Petrol', category: 'light_vehicle' },
  'A-BNS09': { name: '0.5 TONNE BAKKIE 4X2 NISSAN', type: 'Bakkie', fuelType: 'Petrol', category: 'light_vehicle' },
  'A-BNS10': { name: '0.5 TONNE BAKKIE 4X2 NISSAN', type: 'Bakkie', fuelType: 'Petrol', category: 'light_vehicle' },
  'A-BOC106': { name: '0.5 TONNE BAKKIE 4X2 CHEVY', type: 'Bakkie', fuelType: 'Petrol', category: 'light_vehicle' },
  'A-BOC107': { name: '0.5 TONNE BAKKIE 4X2 CHEVY', type: 'Bakkie', fuelType: 'Petrol', category: 'light_vehicle' },
  'A-BOC108': { name: '0.5 TONNE BAKKIE 4X2 CHEVY', type: 'Bakkie', fuelType: 'Petrol', category: 'light_vehicle' },
  'A-BRM11': { name: 'BROOM BROCE RCT-350', type: 'Broom', fuelType: 'Diesel', category: 'cleaning' },
  'A-BRM12': { name: 'BROOM BROCE RCT-350', type: 'Broom', fuelType: 'Diesel', category: 'cleaning' },
  'A-BRM13': { name: 'BROOM BROCE RCT-350', type: 'Broom', fuelType: 'Diesel', category: 'cleaning' },
  'A-BRM14': { name: 'BROOM BROCE RCT-350', type: 'Broom', fuelType: 'Diesel', category: 'cleaning' },
  'A-BTH100': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH104': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH115': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH116': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH118': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH119': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH122': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH123': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH125': { name: '1.0 TONNE BAKKIE 4X2 DC', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH127': { name: '1.0 TONNE BAKKIE 4X2 HI RISE', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH129': { name: '1.0 TONNE BAKKIE 4X2 HI RISE', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH130': { name: '1.0 TONNE BAKKIE 4X2 HI RISE', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH131': { name: '1.0 TONNE BAKKIE 4X2 HI RISE', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH134': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH135': { name: '1.0 TONNE BAKKIE 4X2 DC', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH80': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH81': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH91': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH92': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH94': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH95': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH96': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH97': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTH99': { name: '1.0 TONNE BAKKIE 4X2', type: 'Bakkie', fuelType: 'Diesel', category: 'light_vehicle' },
  'A-BTL08': { name: 'TOYOTA LANDCRUISER', type: 'SUV', fuelType: 'Petrol', category: 'light_vehicle' },
  'A-CFH04': { name: 'CRUSHER FIXED HATFIELD', type: 'Crusher', fuelType: 'Diesel', category: 'crushing' },
  'A-CCK05': { name: 'KLEEMANN MOBICONE MCO 9 S EVO CONE', type: 'Cone Crusher', fuelType: 'Diesel', category: 'crushing' },
  'A-CHR03': { name: 'RM HORIZONTAL IMPACT CRUSHER 100GO', type: 'Impact Crusher', fuelType: 'Diesel', category: 'crushing' },
  'A-CJK06': { name: 'KLEEMANN MOBICAT MC 110 R EVO JAW', type: 'Jaw Crusher', fuelType: 'Diesel', category: 'crushing' },
  'A-CSK01': { name: 'KLEEMANN MOBICAT MC 703 EVO SCREEN', type: 'Screen', fuelType: 'Diesel', category: 'screening' },
  'A-CSM02': { name: 'METSO ST2.8 SCALPER SCREEN', type: 'Screen', fuelType: 'Diesel', category: 'screening' },
  'A-CSC03': { name: 'CHIEFTAIN 600, DOUBLE DECK SCREEN', type: 'Screen', fuelType: 'Diesel', category: 'screening' },
  'A-CSE07': { name: 'CHIPSPREADER ETNYRE', type: 'Chipspreader', fuelType: 'Diesel', category: 'paving' },
  'A-CSE08': { name: 'CHIPSPREADER ETNYRE', type: 'Chipspreader', fuelType: 'Diesel', category: 'paving' },
  'A-CSE09': { name: 'CHIPSPREADER ETNYRE', type: 'Chipspreader', fuelType: 'Diesel', category: 'paving' },
  'A-CSE10': { name: 'CHIPSPREADER ETNYRE', type: 'Chipspreader', fuelType: 'Diesel', category: 'paving' },
  'A-DOK13': { name: 'DOZER KOMATSU D65 20t', type: 'Dozer', fuelType: 'Diesel', category: 'earthmoving' },
  'A-DOK15': { name: 'DOZER KOMATSU D65 20t', type: 'Dozer', fuelType: 'Diesel', category: 'earthmoving' },
  'A-DOK16': { name: 'DOZER KOMATSU D155 40t', type: 'Dozer', fuelType: 'Diesel', category: 'earthmoving' },
  'A-DUT07': { name: 'DUMPER B2000', type: 'Dumper', fuelType: 'Diesel', category: 'hauling' },
  'A-EXK38': { name: 'EXCAVATOR PC500 50t TRACKED', type: 'Excavator', fuelType: 'Diesel', category: 'earthmoving' },
  'A-EXK42': { name: 'EXCAVATOR PC270 27t TRACKED', type: 'Excavator', fuelType: 'Diesel', category: 'earthmoving' },
  'A-EXK44': { name: 'EXCAVATOR PC450 45t TRACKED', type: 'Excavator', fuelType: 'Diesel', category: 'earthmoving' },
  'A-EXK46': { name: 'EXCAVATOR PC350 35t TRACKED', type: 'Excavator', fuelType: 'Diesel', category: 'earthmoving' },
  'A-FDH39': { name: 'FLAT DECK HINO 5t', type: 'Truck', fuelType: 'Diesel', category: 'transport' },
  'A-FDH23': { name: 'FLAT DECK HINO 5t', type: 'Truck', fuelType: 'Diesel', category: 'transport' },
  'A-FDH26': { name: 'FLAT DECK HINO 5t', type: 'Truck', fuelType: 'Diesel', category: 'transport' },
  'A-FDH28': { name: 'FLAT DECK HINO 5t', type: 'Truck', fuelType: 'Diesel', category: 'transport' },
  'A-FDH35': { name: 'FLAT DECK HINO 5t DOUBLE CAB', type: 'Truck', fuelType: 'Diesel', category: 'transport' },
  'A-FDH36': { name: 'FLAT DECK HINO 5t DOUBLE CAB', type: 'Truck', fuelType: 'Diesel', category: 'transport' },
  'A-FDM31': { name: 'FLATBED MAN 26-280 15t CRANE 6t', type: 'Truck', fuelType: 'Diesel', category: 'transport' },
  'A-FLM03': { name: 'MAHAND 3.5TON FORKLIFT', type: 'Forklift', fuelType: 'Diesel', category: 'material_handling' },
  'A-FLT02': { name: '2.5T FORK LIFT TOYOTA', type: 'Forklift', fuelType: 'Diesel', category: 'material_handling' },
  'A-FSH01': { name: 'FLAT DECK HINO 5t', type: 'Truck', fuelType: 'Diesel', category: 'transport' },
  'A-FSH02': { name: 'FLAT DECK HINO 5t', type: 'Truck', fuelType: 'Diesel', category: 'transport' },
  'A-FSH03': { name: 'FLAT DECK HINO 5t', type: 'Truck', fuelType: 'Diesel', category: 'transport' },
  'A-FSH04': { name: 'FLAT DECK HINO 5t', type: 'Truck', fuelType: 'Diesel', category: 'transport' },
  'A-FSN05': { name: 'FLAT DECK NISSAN FUEL TANKER 10000L', type: 'Fuel Tanker', fuelType: 'Diesel', category: 'fuel_trailer' },
  'A-FSI06': { name: 'FLAT DECK ISUZU FUEL TANKER 4000L', type: 'Fuel Tanker', fuelType: 'Diesel', category: 'fuel_trailer' },
  'A-GRC27': { name: 'GRADER CAT 140K', type: 'Grader', fuelType: 'Diesel', category: 'earthmoving' },
  'A-GRC28': { name: 'GRADER CAT 140K', type: 'Grader', fuelType: 'Diesel', category: 'earthmoving' },
  'A-GRC30': { name: 'GRADER CAT 140K with Trimble', type: 'Grader', fuelType: 'Diesel', category: 'earthmoving' },
  'A-GRC32': { name: 'GRADER CAT 140K', type: 'Grader', fuelType: 'Diesel', category: 'earthmoving' },
  'A-GRC33': { name: 'GRADER CAT 140K', type: 'Grader', fuelType: 'Diesel', category: 'earthmoving' },
  'A-GRK34': { name: 'GRADER KOMATSU GD675-5', type: 'Grader', fuelType: 'Diesel', category: 'earthmoving' },
  'A-GRC35': { name: 'GRADER CAT 140K', type: 'Grader', fuelType: 'Diesel', category: 'earthmoving' },
  'A-HOB11': { name: 'HORSE + 26t TIP TRAILER', type: 'Truck & Trailer', fuelType: 'Diesel', category: 'hauling' },
  'A-HOB12': { name: 'HORSE + 26t TIP TRAILER', type: 'Truck & Trailer', fuelType: 'Diesel', category: 'hauling' },
  'A-HOB13': { name: 'HORSE + 26t TIP TRAILER', type: 'Truck & Trailer', fuelType: 'Diesel', category: 'hauling' },
  'A-HOB14': { name: 'HORSE + 26t TIP TRAILER', type: 'Truck & Trailer', fuelType: 'Diesel', category: 'hauling' },
  'A-HOB15': { name: 'HORSE + 26t TIP TRAILER', type: 'Truck & Trailer', fuelType: 'Diesel', category: 'hauling' },
  'A-LLP02': { name: 'POWER PLANT LISTER 55kVA', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-LOC16': { name: 'LOADER CAT 950GC    3,1m³ bucket', type: 'Loader', fuelType: 'Diesel', category: 'earthmoving' },
  'A-LOK18': { name: 'LOADER KOMATSU WA250-6    2,3m³ bucket', type: 'Loader', fuelType: 'Diesel', category: 'earthmoving' },
  'A-LOK19': { name: 'LOADER KOMATSU WA250-6    2,3m³ bucket', type: 'Loader', fuelType: 'Diesel', category: 'earthmoving' },
  'A-LOK20': { name: 'LOADER KOMATSU WA380-6    3m³ bucket', type: 'Loader', fuelType: 'Diesel', category: 'earthmoving' },
  'A-LOK21': { name: 'LOADER KOMATSU WA250-6    2,3m³ bucket', type: 'Loader', fuelType: 'Diesel', category: 'earthmoving' },
  'A-MCL01': { name: 'MOBILE CRANE 35t LIEBHERR', type: 'Crane', fuelType: 'Diesel', category: 'lifting' },
  'A-MIB11': { name: 'MIXER BARFORD 330R DIESEL', type: 'Mixer', fuelType: 'Diesel', category: 'concrete' },
  'A-MIB14': { name: 'MIXER BRIGGS AND STRATTON 175', type: 'Mixer', fuelType: 'Petrol', category: 'concrete' },
  'A-MIL01': { name: 'MIXER LISTER 175 DIESEL', type: 'Mixer', fuelType: 'Diesel', category: 'concrete' },
  'A-MIL17': { name: 'MIXER LISTER 500R', type: 'Mixer', fuelType: 'Diesel', category: 'concrete' },
  'A-MIL18': { name: 'MIXER LISTER 500R', type: 'Mixer', fuelType: 'Diesel', category: 'concrete' },
  'A-MIW03': { name: 'MIXER WINGET 175 DIESEL', type: 'Mixer', fuelType: 'Diesel', category: 'concrete' },
  'A-MIW05': { name: 'MIXER WINGET 175TE DIESEL', type: 'Mixer', fuelType: 'Diesel', category: 'concrete' },
  'A-MIW12': { name: 'MIXER WINGET 330T DIESEL', type: 'Mixer', fuelType: 'Diesel', category: 'concrete' },
  'A-MIW13': { name: 'MIXER WINGET 330T DIESEL', type: 'Mixer', fuelType: 'Diesel', category: 'concrete' },
  'A-MPW03': { name: 'ASPHALT MILL WIRTGEN W100F', type: 'Milling Machine', fuelType: 'Diesel', category: 'paving' },
  'A-MPW04': { name: 'ASPHALT MILL WIRTGEN W200', type: 'Milling Machine', fuelType: 'Diesel', category: 'paving' },
  'A-MRB07': { name: 'RECYCLER Bell MPH125', type: 'Recycler', fuelType: 'Diesel', category: 'paving' },
  'A-MRW04': { name: 'RECYCLER WIRTGEN WR2000', type: 'Recycler', fuelType: 'Diesel', category: 'paving' },
  'A-MRW05': { name: 'RECYCLER WIRTGEN WR240', type: 'Recycler', fuelType: 'Diesel', category: 'paving' },
  'A-MRW06': { name: 'RECYCLER WIRTGEN WR240', type: 'Recycler', fuelType: 'Diesel', category: 'paving' },
  'A-MTM03': { name: 'MAN CONCRETE MIXER 6x4 - 6m3', type: 'Concrete Mixer Truck', fuelType: 'Diesel', category: 'concrete' },
  'A-MTS04': { name: 'SCANIA CONCRETE MIXER 6x4 - 6m3', type: 'Concrete Mixer Truck', fuelType: 'Diesel', category: 'concrete' },
  'A-MTB06': { name: 'M/B REIMER CONCRETE MIXER 8x4 - 8m3', type: 'Concrete Mixer Truck', fuelType: 'Diesel', category: 'concrete' },
  'A-MTB06-1': { name: 'REIMER CONCRETE MIXER DONKEY ENGINE', type: 'Concrete Mixer', fuelType: 'Diesel', category: 'concrete' },
  'A-RPA16': { name: 'PNEUMATIC AMMANN 24t AP240', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RPA17': { name: 'PNEUMATIC AMMANN 24t AP240', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RPA18': { name: 'PNEUMATIC AMMANN 24t AP240', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RPA21': { name: 'PNEUMATIC AMMANN 24t AP240', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RPA22': { name: 'PNEUMATIC AMMANN 24t AP240', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RPC19': { name: 'PNEUMATIC CAT CW34', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RPC20': { name: 'PNEUMATIC CAT CW34', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RPD10': { name: 'PNEUMATIC DYNAPAC 20t CP221', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RPD11': { name: 'PNEUMATIC DYNAPAC 20t CP221', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RPD12': { name: 'PNEUMATIC DYNAPAC 27t CP271', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RPD14': { name: 'PNEUMATIC DYNAPAC 27t CP271', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RPD15': { name: 'PNEUMATIC DYNAPAC 24t CP224', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RPH13': { name: 'PNEUMATIC HAMM 20t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RSD05': { name: 'STATIC DYNAPAC 3-Point 12t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RSD06': { name: 'STATIC DYNAPAC 3-Point 12t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RSD07': { name: 'STATIC DYNAPAC 3-Point 12t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RTA10': { name: 'VIBRATING TANDEM AMMANN 9t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RTH11': { name: 'VIBRATING TANDEM HAMM 4t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RTH13': { name: 'VIBRATING TANDEM HAMM 2,5t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RTH14': { name: 'VIBRATING TANDEM HAMM 9t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RTH15': { name: 'VIBRATING TANDEM HAMM 2,7t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RTH16': { name: 'VIBRATING TANDEM HAMM 2,7t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RVA25': { name: 'VIBRATING AMMANN ASC 100 10t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RVA26': { name: 'VIBRATING AMMANN ACE PRO ASC 110 12t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RVA28': { name: 'VIBRATING AMMANN ASC 170 17t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RVA30': { name: 'VIBRATING AMMANN ASC 200 19t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RVA31': { name: 'VIBRATING AMMANN ASC 200 19t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RVA33': { name: 'VIBRATING AMMANN ACE 100 10t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RVA34': { name: 'VIBRATING AMMANN ACE 100 10t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RVD19': { name: 'VIBRATING DYNAPAC CA512-D 17t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RVD22': { name: 'VIBRATING DYNAPAC CA602 19t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RVH29': { name: 'VIBRATING HAMM 3510 10t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-RVH32': { name: 'VIBRATING HAMM 3520 20t', type: 'Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-SLD2': { name: 'FUEL TRAILER', type: 'Fuel Trailer', fuelType: 'Diesel', category: 'fuel_trailer' },
  'A-SLD3': { name: 'FUEL TRAILER', type: 'Fuel Trailer', fuelType: 'Diesel', category: 'fuel_trailer' },
  'A-SLD7': { name: 'FUEL TRAILER', type: 'Fuel Trailer', fuelType: 'Diesel', category: 'fuel_trailer' },
  'A-SLD09': { name: 'FUEL TRAILER', type: 'Fuel Trailer', fuelType: 'Diesel', category: 'fuel_trailer' },
  'A-SLD10': { name: 'FUEL TRAILER', type: 'Fuel Trailer', fuelType: 'Diesel', category: 'fuel_trailer' },
  'A-SLTD08': { name: 'TANKER CLINIC 32KL DRAWBAR TRAILERS(WATER)', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-SLTD09': { name: 'TANKER CLINIC 32KL DRAWBAR TRAILERS', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-SLTD10': { name: 'TANKER CLINIC 32KL DRAWBAR TRAILERS', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-SLTD11': { name: 'TANKER CLINIC 32KL DRAWBAR TRAILERS', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-SLTD12': { name: 'GRW 29KL DRAWBAR TRAILERS', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-SLTD13': { name: 'TANKER CLINIC 32KL DRAWBAR TRAILERS(WATER)', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-SLW01': { name: 'WATER TRAILER', type: 'Water Trailer', fuelType: 'Water', category: 'water_trailer' },
  'A-SLW03': { name: 'WATER TRAILER', type: 'Water Trailer', fuelType: 'Water', category: 'water_trailer' },
  'A-SLW04': { name: 'WATER TRAILER', type: 'Water Trailer', fuelType: 'Water', category: 'water_trailer' },
  'A-SLW05': { name: 'WATER TRAILER', type: 'Water Trailer', fuelType: 'Water', category: 'water_trailer' },
  'A-SLW06': { name: 'WATER TRAILER', type: 'Water Trailer', fuelType: 'Water', category: 'water_trailer' },
  'A-SLW08': { name: 'WATER TRAILER', type: 'Water Trailer', fuelType: 'Water', category: 'water_trailer' },
  'A-SLW09': { name: 'WATER TRAILER', type: 'Water Trailer', fuelType: 'Water', category: 'water_trailer' },
  'A-SMB11': { name: 'SLURRY MIXER BENZ 3340', type: 'Slurry Mixer', fuelType: 'Diesel', category: 'paving' },
  'A-SMB11-1': { name: 'SLURRY MIXER BENZ 3340 DONKEY ENGINE', type: 'Slurry Mixer', fuelType: 'Diesel', category: 'paving' },
  'A-SMR12': { name: 'MOBILE RADIO TRAILERS', type: 'Radio Trailer', fuelType: 'None', category: 'support' },
  'A-SPW01': { name: 'PRESSURE WASHER TRAILER', type: 'Pressure Washer', fuelType: 'Diesel', category: 'cleaning' },
  'A-SPW02': { name: 'PRESSURE WASHER TRAILER', type: 'Pressure Washer', fuelType: 'Diesel', category: 'cleaning' },
  'A-SPW03': { name: 'PRESSURE WASHER TRAILER', type: 'Pressure Washer', fuelType: 'Diesel', category: 'cleaning' },
  'A-SPW04': { name: 'PRESSURE WASHER TRAILER', type: 'Pressure Washer', fuelType: 'Diesel', category: 'cleaning' },
  'A-SSP03': { name: 'SEMI TRAILER MOBILE WORKSHOP', type: 'Mobile Workshop', fuelType: 'None', category: 'support' },
  'A-STH14': { name: 'HINO SERVICE TRUCKS', type: 'Service Truck', fuelType: 'Diesel', category: 'support' },
  'A-STL23': { name: 'GENERATOR TRAILER', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-STD01': { name: 'STATIC TANK DIESEL 23m3', type: 'Static Tank', fuelType: 'Diesel', category: 'static_tank' },
  'A-STD02': { name: 'STATIC TANK DIESEL 23m3', type: 'Static Tank', fuelType: 'Diesel', category: 'static_tank' },
  'A-STD05': { name: 'STATIC TANK DIESEL 23m3', type: 'Static Tank', fuelType: 'Diesel', category: 'static_tank' },
  'A-STT10': { name: 'HINO SERVICE TRUCKS', type: 'Service Truck', fuelType: 'Diesel', category: 'support' },
  'A-TAD01': { name: 'DOOSAN DA30 ADT 30t', type: 'Articulated Dump Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TAD02': { name: 'DOOSAN DA30 ADT 30t', type: 'Articulated Dump Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TAD03': { name: 'DOOSAN DA30 ADT 30t', type: 'Articulated Dump Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TAC04': { name: 'CAT 730 ADT 30t', type: 'Articulated Dump Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TAC05': { name: 'CAT 730 ADT 30t', type: 'Articulated Dump Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TAC06': { name: 'CAT 730 ADT 30t', type: 'Articulated Dump Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TAC07': { name: 'CAT 730 ADT 30t', type: 'Articulated Dump Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TAC08': { name: 'CAT 730 ADT 30t', type: 'Articulated Dump Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TAC09': { name: 'CAT 730 ADT 30t', type: 'Articulated Dump Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TAK10': { name: 'KOMATSU HM400 ADT 40t', type: 'Articulated Dump Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TAK11': { name: 'KOMATSU HM400 ADT 40t', type: 'Articulated Dump Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TAK12': { name: 'KOMATSU HM400 ADT 40t', type: 'Articulated Dump Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS10': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS11': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS12': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS13': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS14': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS15': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS16': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS17': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS18': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS19': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS20': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS21': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS22': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS23': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS24': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS25': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS26': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS27': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS28': { name: 'SCANIA 8x4 15m3 Tipper Only', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS29': { name: 'SCANIA 8x4 15m3 Tipper Only', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS07': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS08': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-THS09': { name: 'SCANIA 8x4 15m3 Tipper & Trailer', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TIB69': { name: 'BENZ 33-35 12M3 TIPPER 6X4', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TIB70': { name: 'BENZ 33-35 12M3 TIPPER 6X4', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TIS47': { name: 'SCANIA P410 17M3 TIPPER 8X4', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TIS48': { name: 'SCANIA P410 17M3 TIPPER 8X4', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TIS49': { name: 'SCANIA P410 17M3 TIPPER 8X4', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TIS50': { name: 'SCANIA P410 17M3 TIPPER 8X4', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TIS51': { name: 'SCANIA P410 17M3 TIPPER 8X4', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TIS52': { name: 'SCANIA P410 17M3 TIPPER 8X4', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TIS68': { name: 'SCANIA P360 12M3 TIPPER 6X4', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TIS71': { name: 'SCANIA G460 20M3 TIPPER 8X4', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TIS72': { name: 'SCANIA G460 20M3 TIPPER 8X4', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TIS74': { name: 'SCANIA G460 20M3 TIPPER 8X4', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TLJ29': { name: 'TLB JCB 3CX 4X4 6.4t', type: 'TLB', fuelType: 'Diesel', category: 'earthmoving' },
  'A-TLJ31': { name: 'TLB JCB 3CX 4X4 6.4t', type: 'TLB', fuelType: 'Diesel', category: 'earthmoving' },
  'A-TLM01': { name: 'MANITOU MT932', type: 'Telehandler', fuelType: 'Diesel', category: 'material_handling' },
  'A-TSF31': { name: 'FUSO 4X2 6M3 TIPPER', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TSF32': { name: 'FUSO 4X2 6M3 TIPPER', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TSF33': { name: 'FUSO 4X2 6M3 TIPPER', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TSV45': { name: 'VW 17-250 4x2 6M3 TIPPER', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-TSV46': { name: 'VW 17-250 4x2 6M3 TIPPER', type: 'Tipper Truck', fuelType: 'Diesel', category: 'hauling' },
  'A-WTB36': { name: 'WATER TANKER MERC 2628', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-WTM21': { name: 'WATER TANKER 16KL  MAN CLA 26,280', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-WTM23': { name: 'WATER TANKER 16KL  MAN CLA 26,280', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-WTM27': { name: 'WATER TANKER 16KL  MAN CLA 26,280', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-WTM30': { name: 'WATER TANKER 16KL  MAN CLA 26,280', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-WTM32': { name: 'WATER TANKER 16KL  MAN CLA 26,280', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-WTM33': { name: 'WATER TANKER 16KL  MAN CLA 26,280', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-WTM34': { name: 'WATER TANKER 16KL  MAN CLA 26,280', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-WTM35': { name: 'WATER TANKER 16KL  MAN CLA 26,280', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-WTM38': { name: 'WATER TANKER 16KL  MAN CLA 26,280', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-WTS37': { name: 'WATER TANKER 30KL  SCANIA P410 8X4', type: 'Water Tanker', fuelType: 'Water', category: 'water_trailer' },
  'A-ZBH03': { name: 'BACKPACK BLOWER HUSQVARNA', type: 'Blower', fuelType: 'Petrol', category: 'landscaping' },
  'A-ZBH04': { name: 'BACKPACK BLOWER HUSQVARNA', type: 'Blower', fuelType: 'Petrol', category: 'landscaping' },
  'A-ZBH05': { name: 'BACKPACK BLOWER HUSQVARNA', type: 'Blower', fuelType: 'Petrol', category: 'landscaping' },
  'A-ZBP01': { name: 'BITUMEN PUMP', type: 'Pump', fuelType: 'Diesel', category: 'paving' },
  'A-ZBP02': { name: 'BITUMEN PUMP 2"', type: 'Pump', fuelType: 'Diesel', category: 'paving' },
  'A-ZBP03': { name: 'BITUMEN PUMP 2"', type: 'Pump', fuelType: 'Diesel', category: 'paving' },
  'A-ZBP05': { name: 'BITUMEN PUMP 2"', type: 'Pump', fuelType: 'Diesel', category: 'paving' },
  'A-ZCFD01': { name: 'CARRIER FRAME DIESEL TANK 5000L', type: 'Fuel Tank', fuelType: 'Diesel', category: 'fuel_trailer' },
  'A-ZCH07': { name: 'CONCRETE SAW HONDA GX240', type: 'Concrete Saw', fuelType: 'Petrol', category: 'concrete' },
  'A-ZCH08': { name: 'CONCRETE SAW HONDA GX240', type: 'Concrete Saw', fuelType: 'Petrol', category: 'concrete' },
  'A-ZCH09': { name: 'CONCRETE SAW HONDA GX240', type: 'Concrete Saw', fuelType: 'Petrol', category: 'concrete' },
  'A-ZCJ01': { name: 'CONVEYOR TRAILER', type: 'Conveyor', fuelType: 'Diesel', category: 'material_handling' },
  'A-ZCJ02': { name: 'CONVEYOR TRAILER', type: 'Conveyor', fuelType: 'Diesel', category: 'material_handling' },
  'A-ZCT03': { name: 'CONVEYOR BELT', type: 'Conveyor', fuelType: 'Electric', category: 'material_handling' },
  'A-ZCT04': { name: 'CONCRETE SAW TURNER MORRIS', type: 'Concrete Saw', fuelType: 'Petrol', category: 'concrete' },
  'A-ZCT05': { name: 'CONCRETE SAW TURNER MORRIS', type: 'Concrete Saw', fuelType: 'Petrol', category: 'concrete' },
  'A-ZCT06': { name: 'CONCRETE SAW TURNER MORRIS', type: 'Concrete Saw', fuelType: 'Petrol', category: 'concrete' },
  'A-ZCV07': { name: 'CONCRETE SAW HONDA', type: 'Concrete Saw', fuelType: 'Petrol', category: 'concrete' },
  'A-ZFF01': { name: 'FIRE FIGHTING UNIT', type: 'Fire Fighting Unit', fuelType: 'Diesel', category: 'safety' },
  'A-ZFF02': { name: 'FIRE FIGHTING UNIT', type: 'Fire Fighting Unit', fuelType: 'Diesel', category: 'safety' },
  'A-ZFF03': { name: 'FIRE FIGHTING UNIT', type: 'Fire Fighting Unit', fuelType: 'Diesel', category: 'safety' },
  'A-ZFH01': { name: 'FLOOR GRINDER', type: 'Floor Grinder', fuelType: 'Electric', category: 'concrete' },
  'A-ZFH02': { name: 'FLOOR GRINDER', type: 'Floor Grinder', fuelType: 'Electric', category: 'concrete' },
  'A-ZFR01': { name: 'POWER FLOAT', type: 'Power Float', fuelType: 'Petrol', category: 'concrete' },
  'A-ZFR02': { name: 'POWER FLOAT BRIGGS & STRATTON', type: 'Power Float', fuelType: 'Petrol', category: 'concrete' },
  'A-ZFR03': { name: 'POWER FLOAT ROBIN', type: 'Power Float', fuelType: 'Petrol', category: 'concrete' },
  'A-ZFR04': { name: 'POWER FLOAT ROBIN', type: 'Power Float', fuelType: 'Petrol', category: 'concrete' },
  'A-ZGB10': { name: 'GENSET 220V B & STRATTON', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGB12': { name: 'GENSET 220V B & STRATTON', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGB14': { name: 'GENSET 220V B & STRATTON', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGB15': { name: 'GENSET 220V B & STRATTON', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGB25': { name: 'GENSET 220V B & STRATTON', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGB28': { name: 'GENSET 220V B & STRATTON', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGB30': { name: 'GENSET 220V B & STRATTON', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGB64': { name: 'GENSET 220V B & STRATTON', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGC17': { name: 'GENSET 100kVA CATERPILLAR', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGD57': { name: 'GENSET DUETZ 100kVA', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGD59': { name: 'GENSET DUETZ 30kVA', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGD60': { name: 'GENSET DUETZ 30kVA', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGE41': { name: 'GENSET ELEGEN', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGH20': { name: 'GENERATOR HONDA GX160', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGH22': { name: 'GENSET HONDA SPOT LIGHT TRAILER', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGH27': { name: 'GENERATOR HONDA 2.2KVA GX160', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGH31': { name: 'GENSET HONDA', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGH33': { name: 'GENSET HONDA', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGH37': { name: 'GENSET HONDA', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGH45': { name: 'GENSET HONDA', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGH48': { name: 'GENERATOR 10KVA 3 PHASE', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGH69': { name: 'GENSET HONDA', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGH70': { name: 'GENSET HONDA', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGK01': { name: 'GENERATOR 8KVA 3 PHASE', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGP47': { name: 'GEN KING 60kVA', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGR04': { name: 'GENSET ROBIN CORE DRILL', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGR05': { name: 'GENSET ROBIN CORE DRILL', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGR59': { name: 'GENSET ROBIN', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGR60': { name: 'GENSET ROBIN', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGR61': { name: 'GENERATOR 8KVA 3 PHASE', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGS49': { name: 'GENSET 500kVA SCANIA', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGS50': { name: 'GENSET SKY-GO', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGS52': { name: 'GENSET 500kVA SCANIA', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGS53': { name: 'GENSET 500kVA SCANIA', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGS58': { name: 'GENSET 400kVA SCANIA', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGU33': { name: 'GENERATOR UNIPOWER 5500-52 5.5', type: 'Generator', fuelType: 'Petrol', category: 'power' },
  'A-ZGV06': { name: 'GENSET VOLVO 60kVA', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGV15': { name: 'GENSET 200kVA VOLVO', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGV32': { name: 'GENSET 400kVA VOLVO', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGY23': { name: 'GENERATOR YANMAR', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGY64': { name: 'GENERATOR YANMAR', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZGY65': { name: 'GENERATOR YANMAR', type: 'Generator', fuelType: 'Diesel', category: 'power' },
  'A-ZHBS01': { name: 'HAND HELD BROOM STIHL', type: 'Broom', fuelType: 'Petrol', category: 'cleaning' },
  'A-ZHBS02': { name: 'HAND HELD BROOM STIHL', type: 'Broom', fuelType: 'Petrol', category: 'cleaning' },
  'A-ZJB07': { name: 'CONCRETE BREAKER', type: 'Concrete Breaker', fuelType: 'Electric', category: 'demolition' },
  'A-ZJB09': { name: 'CONCRETE BREAKER', type: 'Concrete Breaker', fuelType: 'Electric', category: 'demolition' },
  'A-ZJB10': { name: 'CONCRETE BREAKER', type: 'Concrete Breaker', fuelType: 'Electric', category: 'demolition' },
  'A-ZJB11': { name: 'CONCRETE BREAKER', type: 'Concrete Breaker', fuelType: 'Electric', category: 'demolition' },
  'A-ZJH12': { name: 'CONCRETE BREAKER', type: 'Concrete Breaker', fuelType: 'Electric', category: 'demolition' },
  'A-ZLC01': { name: 'LAB CENTRIFUGE', type: 'Lab Equipment', fuelType: 'Electric', category: 'lab' },
  'A-ZLC02': { name: 'LAB CENTRIFUGE', type: 'Lab Equipment', fuelType: 'Electric', category: 'lab' },
  'A-ZLC03': { name: 'LAB CENTRIFUGE', type: 'Lab Equipment', fuelType: 'Electric', category: 'lab' },
  'A-ZLC04': { name: 'LAB CENTRIFUGE', type: 'Lab Equipment', fuelType: 'Electric', category: 'lab' },
  'A-ZLH01': { name: 'TOWER LIGHT HONDA HOME BUILT', type: 'Tower Light', fuelType: 'Petrol', category: 'lighting' },
  'A-ZLG02': { name: 'TOWER LIGHT GENERAC VTEVO', type: 'Tower Light', fuelType: 'Petrol', category: 'lighting' },
  'A-ZLG03': { name: 'TOWER LIGHT GENERAC VTEVO', type: 'Tower Light', fuelType: 'Petrol', category: 'lighting' },
  'A-ZLY04': { name: 'TOWER LIGHT YANMAR HOME BUILD', type: 'Tower Light', fuelType: 'Diesel', category: 'lighting' },
  'A-ZLY05': { name: 'TOWER LIGHT YANMAR HOME BUILD', type: 'Tower Light', fuelType: 'Diesel', category: 'lighting' },
  'A-ZPB40': { name: '3INCH BRIGGS & STRATTON PUMP', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPB43': { name: 'WATER PUMP 4" B & STRATTON', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPB49': { name: 'WATER PUMP 2" B & STRATTON', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPB51': { name: 'WATER PUMP 2" B & STRATTON', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPB72': { name: '3INCH BRIGGS & STRATTON PUMP', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPB73': { name: '3INCH BRIGGS & STRATTON PUMP', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPB80': { name: '3INCH BRIGGS & STRATTON PUMP', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPCB01': { name: 'PLATE COMPACTOR', type: 'Plate Compactor', fuelType: 'Petrol', category: 'compaction' },
  'A-ZPCH02': { name: 'PLATE COMPACTOR HOFFMANN', type: 'Plate Compactor', fuelType: 'Petrol', category: 'compaction' },
  'A-ZPCH03': { name: 'PLATE COMPACTOR HOFFMANN', type: 'Plate Compactor', fuelType: 'Petrol', category: 'compaction' },
  'A-ZPCH04': { name: 'PLATE COMPACTOR HOFFMANN', type: 'Plate Compactor', fuelType: 'Petrol', category: 'compaction' },
  'A-ZPCH05': { name: 'PLATE COMPACTOR HOFFMANN', type: 'Plate Compactor', fuelType: 'Petrol', category: 'compaction' },
  'A-ZPD01': { name: 'POKER DIASTAR KS20', type: 'Poker Vibrator', fuelType: 'Petrol', category: 'concrete' },
  'A-ZPF01': { name: 'WATER PUMP 6" FORD', type: 'Water Pump', fuelType: 'Diesel', category: 'pumping' },
  'A-ZPF02': { name: 'WATER PUMP VARIABLE FIAT', type: 'Water Pump', fuelType: 'Diesel', category: 'pumping' },
  'A-ZPF03': { name: 'WATER PUMP 3 INCH PERKINS', type: 'Water Pump', fuelType: 'Diesel', category: 'pumping' },
  'A-ZPF04': { name: 'WATER PUMP 4" FIAT', type: 'Water Pump', fuelType: 'Diesel', category: 'pumping' },
  'A-ZPH35': { name: 'WATER PUMP 3" HONDA', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH45': { name: 'WATER PUMP 4" HOFFMANN', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH47': { name: 'WATER PUMP 4" HOFFMANN', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH52': { name: 'WATER PUMP 3 INCH HOFFMAN', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH61': { name: 'WATER PUMP 3 INCH HONDA', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH74': { name: 'WATER PUMP 3 INCH HONDA', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH75': { name: 'WATER PUMP 3 INCH HONDA', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH76': { name: 'WATER PUMP 3 INCH HONDA', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH77': { name: 'WATER PUMP 2 INCH HONDA', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH81': { name: 'WATER PUMP 4" HONDA', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH82': { name: 'WATER PUMP 4" HONDA', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH83': { name: 'WATER PUMP 4" HONDA', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH86': { name: 'WATER PUMP 2 INCH HONDA', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH87': { name: 'WATER PUMP 4 INCH HOFFMAN', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH88': { name: 'WATER PUMP 4 INCH HOFFMAN', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH89': { name: 'WATER PUMP 4 INCH HOFFMAN', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPH90': { name: 'WATER PUMP 4 INCH HOFFMAN', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPK63': { name: 'WATER PUMP 4" Electrical', type: 'Water Pump', fuelType: 'Electric', category: 'pumping' },
  'A-ZPL28': { name: 'WATER PUMP 3" LAUNTOP', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPL3': { name: 'WATER PUMP DRIVE UNIT LISTER DIESEL', type: 'Water Pump', fuelType: 'Diesel', category: 'pumping' },
  'A-ZPL62': { name: 'WATER PUMP 3 INCH LAUNTOP', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPP01': { name: 'WATER PUMP 3" PETTER', type: 'Water Pump', fuelType: 'Diesel', category: 'pumping' },
  'A-ZPP03': { name: 'WATER PUMP 3" PERKINS', type: 'Water Pump', fuelType: 'Diesel', category: 'pumping' },
  'A-ZPP04': { name: 'WATER PUMP 3" PERKINS', type: 'Water Pump', fuelType: 'Diesel', category: 'pumping' },
  'A-ZPP59': { name: 'WATER PUMP 6" PERKINS', type: 'Water Pump', fuelType: 'Diesel', category: 'pumping' },
  'A-ZPR60': { name: 'WATER PUMP 4" ROBIN SLUDGE', type: 'Water Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZPWH06': { name: 'PRESSURE WASHER', type: 'Pressure Washer', fuelType: 'Petrol', category: 'cleaning' },
  'A-ZPWH07': { name: 'PRESSURE WASHER', type: 'Pressure Washer', fuelType: 'Petrol', category: 'cleaning' },
  'A-ZPWH08': { name: 'PRESSURE WASHER', type: 'Pressure Washer', fuelType: 'Petrol', category: 'cleaning' },
  'A-ZPWH74': { name: 'PRESSURE WASHER', type: 'Pressure Washer', fuelType: 'Petrol', category: 'cleaning' },
  'A-ZPY53': { name: 'WATER PUMP 3" YANMAR', type: 'Water Pump', fuelType: 'Diesel', category: 'pumping' },
  'A-ZPY84': { name: 'WATER PUMP 3" YANMAR', type: 'Water Pump', fuelType: 'Diesel', category: 'pumping' },
  'A-ZPY85': { name: 'WATER PUMP 3" YANMAR', type: 'Water Pump', fuelType: 'Diesel', category: 'pumping' },
  'A-ZRB21': { name: 'WALK-BEHIND ROLL BOMAG BW65', type: 'Walk-Behind Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-ZRB23': { name: 'WALK-BEHIND ROLL BOMAG BW65', type: 'Walk-Behind Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-ZRB25': { name: 'WALK-BEHIND ROLL BOMAG BW65H', type: 'Walk-Behind Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-ZRB38': { name: 'WALK-BEHIND ROLL BOMAG BW65H', type: 'Walk-Behind Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-ZRB39': { name: 'WALK-BEHIND ROLL BOMAG BW61', type: 'Walk-Behind Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-ZRB40': { name: 'WALK-BEHIND ROLL BOMAG BW61', type: 'Walk-Behind Roller', fuelType: 'Diesel', category: 'compaction' },
  'A-ZRH52': { name: 'RAMMER', type: 'Rammer', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRH53': { name: 'RAMMER', type: 'Rammer', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRM43': { name: 'RAMMER', type: 'Rammer', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRM44': { name: 'RAMMER', type: 'Rammer', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRM45': { name: 'RAMMER', type: 'Rammer', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRM46': { name: 'RAMMER', type: 'Rammer', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRM47': { name: 'RAMMER', type: 'Rammer', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRS01': { name: 'PAINT STRIPPER', type: 'Paint Stripper', fuelType: 'Electric', category: 'maintenance' },
  'A-ZRW31': { name: 'WACKER-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRW33': { name: 'WACKER-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRW36': { name: 'WACKER-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRW54': { name: 'WACKER-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRW55': { name: 'WACKER-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRW56': { name: 'WACKER-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRW57': { name: 'WACKER-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRW58': { name: 'WACKER-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRW59': { name: 'WACKER-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRW60': { name: 'WACKER-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRW61': { name: 'WACKER-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRW62': { name: 'WACKER-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRW63': { name: 'WACKER-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRY38': { name: 'RAMMER YAMAHA', type: 'Rammer', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRY48': { name: 'RAMMER YAMAHA', type: 'Rammer', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRY49': { name: 'RAMMER YAMAHA', type: 'Rammer', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRH50': { name: 'RAMMER HOFFMANN', type: 'Rammer', fuelType: 'Petrol', category: 'compaction' },
  'A-ZRH51': { name: 'RAMMER HOFFMANN', type: 'Rammer', fuelType: 'Petrol', category: 'compaction' },
  'A-ZSF01': { name: 'SUBMERSIBLE PUMP', type: 'Submersible Pump', fuelType: 'Electric', category: 'pumping' },
  'A-ZTS05': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS06': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS07': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS08': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS09': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS10': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS12': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS13': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS14': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS15': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS16': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS17': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS18': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS19': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS20': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS21': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZTS22': { name: 'HOMPIE POMPIE', type: 'Pump', fuelType: 'Petrol', category: 'pumping' },
  'A-ZVB05': { name: 'DRIVE UNIT BRIGGS & STRATTON', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVB10': { name: 'DRIVE UNIT BRIGGS & STRATTON', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVB15': { name: 'DRIVE UNIT BRIGGS & STRATTON', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVB16': { name: 'DRIVE UNIT BRIGGS & STRATTON', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVB19': { name: 'DRIVE UNIT BRIGGS & STRATTON', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVB21': { name: 'DRIVE UNIT BRIGGS & STRATTON', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVB36': { name: 'DRIVE UNIT BRIGGS & STRATTON', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVD12': { name: 'DRIVE UNIT DEK', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVH23': { name: 'DRIVE UNIT HONDA', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVH27': { name: 'DRIVE UNIT HONDA', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVH32': { name: 'DRIVE UNIT HONDA', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVH38': { name: 'DRIVE UNIT HONDA', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVH39': { name: 'DRIVE UNIT HONDA', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVR22': { name: 'DRIVE UNIT ROBIN', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVR31': { name: 'DRIVE UNIT ROBIN', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVR33': { name: 'DRIVE UNIT ROBIN', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVR43': { name: 'DRIVE UNIT ROBIN', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVR44': { name: 'DRIVE UNIT ROBIN', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZVY40': { name: 'DRIVE UNIT YANMAR', type: 'Drive Unit', fuelType: 'Diesel', category: 'power' },
  'A-ZVY41': { name: 'DRIVE UNIT YANMAR', type: 'Drive Unit', fuelType: 'Diesel', category: 'power' },
  'A-ZVY42': { name: 'DRIVE UNIT YANMAR', type: 'Drive Unit', fuelType: 'Diesel', category: 'power' },
  'A-ZVY62': { name: 'DRIVE UNIT YANMAR', type: 'Drive Unit', fuelType: 'Diesel', category: 'power' },
  'A-ZVW35': { name: 'DRIVE UNIT WACKER', type: 'Drive Unit', fuelType: 'Petrol', category: 'power' },
  'A-ZWH21': { name: 'GENSET WELDER HONDA', type: 'Welder Generator', fuelType: 'Petrol', category: 'welding' },
  'A-ZWH24': { name: 'HONDA-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZWH25': { name: 'HONDA-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZWH32': { name: 'HONDA-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZWH42': { name: 'HONDA-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZWH43': { name: 'HONDA-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZWH44': { name: 'HONDA-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZWH45': { name: 'HONDA-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZWH46': { name: 'HONDA-WACKER/ELEPHANT FOOT', type: 'Vibratory Plate', fuelType: 'Petrol', category: 'compaction' },
  'A-ZWH56': { name: 'GENSET WELDER HONDA', type: 'Welder Generator', fuelType: 'Petrol', category: 'welding' },
  'A-ZWY01': { name: 'GENSET WELDER YAMAHA', type: 'Welder Generator', fuelType: 'Petrol', category: 'welding' },
};

// Helper functions
export const vehicleCategories = [...new Set(Object.values(plantMasterList).map(p => p.category))];
export const fuelTypes = [...new Set(Object.values(plantMasterList).map(p => p.fuelType))];
export const plantTypes = [...new Set(Object.values(plantMasterList).map(p => p.type))];

// Utility functions
export const getCategoryColor = (category) => {
  const colors = {
    earthmoving: '#4caf50',
    hauling: '#2196f3',
    paving: '#ff9800',
    crushing: '#9c27b0',
    screening: '#673ab7',
    transport: '#f44336',
    light_vehicle: '#00bcd4',
    specialized: '#ff5722',
    plant: '#8bc34a',
    cleaning: '#795548',
    landscaping: '#607d8b',
    fuel_trailer: '#9e9e9e',
    static_tank: '#3f51b5',
    water_trailer: '#2196f3',
    material_handling: '#ff9800',
    compaction: '#9c27b0',
    concrete: '#795548',
    power: '#f44336',
    welding: '#ff5722',
    lifting: '#673ab7',
    safety: '#d32f2f',
    lab: '#7b1fa2',
    lighting: '#ff9800',
    pumping: '#0288d1',
    demolition: '#616161',
    maintenance: '#78909c',
    support: '#455a64',
    other: '#cccccc'
  };
  return colors[category] || '#cccccc';
};

export const getCategoryIcon = (category) => {
  const icons = {
    'earthmoving': '🚜',
    'hauling': '🚚',
    'paving': '🛣️',
    'crushing': '🗜️',
    'screening': '🔲',
    'transport': '🚐',
    'light_vehicle': '🚙',
    'specialized': '🔧',
    'plant': '🏭',
    'cleaning': '🧹',
    'landscaping': '🌿',
    'fuel_trailer': '⛽',
    'static_tank': '📦',
    'water_trailer': '💧',
    'material_handling': '📦',
    'compaction': '⚖️',
    'concrete': '🏗️',
    'power': '⚡',
    'welding': '🔥',
    'lifting': '🏗️',
    'safety': '🚨',
    'lab': '🔬',
    'lighting': '💡',
    'pumping': '🚰',
    'demolition': '🔨',
    'maintenance': '🔧',
    'support': '🛠️',
    'other': '🚗'
  };
  return icons[category] || '🚗';
};